version: "3"
services: 
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0
    hostname: zookeeper
    container_name: zookeeper    
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000      
  broker:
    image: confluentinc/cp-kafka:5.5.0
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper    
    ports:
     - "29092:29092"
     - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  nifi:
    image: apache/nifi:latest    
    ports:
      - '3000:8080'
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
  elastic:
   image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
   environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
   ulimits:
      memlock:
        soft: -1
        hard: -1
   volumes:
      - data01:/usr/share/elasticsearch/data
   ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.1
    ports:
      - 5601:5601
    depends_on:
      - elastic
    environment:
      ELASTICSEARCH_HOSTS: http://elastic:9200
  #spark:
  #  image: bitnami/spark:latest
  #  environment:
  #    - SPARK_MODE=master
  #    - SPARK_RPC_AUTHENTICATION_ENABLED=no
  #    - SPARK_RPC_ENCRYPTION_ENABLED=no
  #    - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
  #    - SPARK_SSL_ENABLED=no
  #  ports:
  #    - '8080:8080'
  #  depends_on:
  #    - broker
  #spark-worker:
  #  image: bitnami/spark:latest
  #  environment:
  #    - SPARK_MODE=worker
  #    - SPARK_MASTER_URL=spark://spark:7077
  #    - SPARK_WORKER_MEMORY=1G
  #    - SPARK_WORKER_CORES=1
  #    - SPARK_RPC_AUTHENTICATION_ENABLED=no
  #    - SPARK_RPC_ENCRYPTION_ENABLED=no
  #    - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
  #    - SPARK_SSL_ENABLED=no
  #  depends_on:
  #    - spark
volumes:
  data01:
    driver: local
